### ISSUE TITLE
Dialog stack errors and suggestions

### ISSUE THREAD

**Issue by tmedwards** [BawdyInkSlinger/dialog-element-macro#1]
# Errors

https://github.com/BawdyInkSlinger/dialog-element-macro/blob/ef08686c5e9ff89371890d598978304e06f520cc/src/dialog-stack.ts#L3-L5

https://github.com/BawdyInkSlinger/dialog-element-macro/blob/ef08686c5e9ff89371890d598978304e06f520cc/src/dialog-stack.ts#L9-L13

These tests should be inverted.  I.e., create the stack state if the stack **does not** exist and throw an error if the stack **does not** exist.  E.g., in both cases:

```js
    if (!this.dialogStackExists()) {
```

The only reason they work currently is because the return value of the `.dialogStackExists()` method is backwards.  I.e., it returns `true` if the stack **does not** exist, contrary to its name.

https://github.com/BawdyInkSlinger/dialog-element-macro/blob/ef08686c5e9ff89371890d598978304e06f520cc/src/dialog-stack.ts#L17-L20

E.g., its return should be something like:

```js
    return (
      State.temporary?.dialog_element_macro_stack !== null &&
      State.temporary?.dialog_element_macro_stack !== undefined
    );
```

That said.  The return is kind of cursed for other reasons as well.

1. Checking for the existence of `State.temporary` is pointless, since it always exists.  I.e., you don't need the optional chaining operator there.
2. The idiomatic way to test for nullish-ness is to use the lazy (in)equality operator (`==` & `!=`) on `null`, which handles both cases at once.

E.g., putting both together:

```js
    return State.temporary.dialog_element_macro_stack != null; // lazy equality for null
```

Even if you don't like the idea of using lazy (in)equality to test for nullish-ness, I'd still drop the use of optional chaining.

----

# Suggestions

https://github.com/BawdyInkSlinger/dialog-element-macro/blob/ef08686c5e9ff89371890d598978304e06f520cc/src/dialog-stack.ts#L16

This name is cursed.  It's an object method, not a standalone function.  Why not simply call it `exists` or something similar?  E.g.,

```js
/* BAD */
DialogElementMacroStack.dialogStackExists()

/* GOOD */
DialogElementMacroStack.exists()
```

Even if it's unused externally&zwj;**†** the change would make its internal usage less needlessly verbose.

**†**  GitHub was indexing the repo at the time, so I couldn't check to see.  Though, as a follow up question: if it *is* unused externally, why expose it at all?

----

As a final idea, if not an outright suggestion.  In the few built-in macros that keep state within story or temporary variables, I personally prefer to ensure that user code is unlikely to ever touch said state by making the property name something that cannot be accessed via the chaining operator, which also means via sigil.  E.g.,

```js
/* INSTEAD OF */
State.temporary.dialog_element_macro_stack

/* USE SOMETHING LIKE */
State.temporary['#dialog_element_macro_stack']
```

If the stack state is accessed external to this object's exported API&zwj;**†**, then you could always add a method to return its value so consumers don't need to be aware of the details.

**†**  GitHub was still indexing the repo, so I couldn't check on this.

**Comment by BawdyInkSlinger** [comment]
> The idiomatic way to test for nullish-ness is to use the lazy (in)equality operator (== & !=) on null, which handles both cases at once.

Neat. TIL.

> † GitHub was indexing the repo at the time, so I couldn't check to see. Though, as a follow up question: if it is unused externally, why expose it at all?

Here's why: I was rushing and hadn't noticed. :)

I've attempted to implement all your suggestions. Thanks for making them.
